### ISSUE TITLE
G code strings

### ISSUE THREAD

**Issue by ghost** [ivan-radic/udl-documentation#10]
In G-code, commands like M117 have strings. How can we use User Defined Language to highlight a string as in 
`M117 Raising Z for travel`

without highlighting sin , Z , g , etc all different colours?
Can the documentation please cover this a little more explicitly. 
Thanks

**Comment by ivan-radic** [comment]
Hi Lindsay,

I know nothing about G-code. Can you explain what string is in your example:

`M117 Raising Z for travel`

Regards,
Ivan

**Comment by ivan-radic** [comment]
Hi again,

in case this whole line should be treated as a string, you may define it as a Delimiter, see example 2 here: https://ivan-radic.github.io/udl-documentation/delimiters/,.
Delimiters should start with `M117` and extend to the end of line `((EOL))`.
If you need to force `M117` to trigger strings only at the beginning of line, use Line comments instead of Delimiters.

Regards,
Ivan

**Comment by ghost** [comment]
Hi Ivan,
Gcode is a simple language for operating machines like 3D printers or multi axis Milling machines.

When the M117 keyword is encountered, everything else on the line is considered to be a string (except for comments)


Lindsay ;-)

**Comment by ghost** [comment]
Except M117 is not a delimiter, it’s a function, and the string that follows, including spaces, is the argument of that function. 

So if I have:
M117 this is the string 
M117 should have the colour for functions.
And
This is a string 
Should have the colour for strings.

Thanks for your help.

I’m guessing from your reply that this is not possible with Notepad++’s UDL. If I make M117 an opening delimiter with an EOL as the closing delimiter then the whole line will be rendered one colour, which is incorrect.



Lindsay ;-)

**Comment by ivan-radic** [comment]
Hi Lindsay,

thanks for clearing it up. In UDL 2.1 this is indeed not possible. 

On a side note, I really should reorganize my life to prioritize development of UDL 3.0, which will support such functionality. For now you have a simple choice of rendering whole line as one color (by using Delimiters or Line comments) or leaving it uncolored.

Regards,
Ivan
