### ISSUE TITLE
Folding in comment : Folding in code : errors

### ISSUE THREAD

**Issue by manufv** [ivan-radic/udl-documentation#11]
hi,
I try to define UDL for Rocket/Universe/uniBASIC.
The folding in comment and the folding in code do not work.

here the show of the folding errors
![fold errors](https://user-images.githubusercontent.com/4491759/75888749-245f0380-5e2c-11ea-94c1-a53f7b026ca2.png)

here the language defn to import into npp : [uniBASIC.npp.xml.txt](https://github.com/ivan-radic/udl-documentation/files/4287741/uniBASIC.npp.xml.txt)

here the source code for your evaluation. [SP_ASSIGN_INFODATA.txt](https://github.com/ivan-radic/udl-documentation/files/4287755/SP_ASSIGN_INFODATA.txt)

I hope you can help.
Thanks by advance.
manuFV

**Comment by ivan-radic** [comment]
Hi Manu,

try deleting definition of "Comment style". 
Instead set the same thing as Delimiter 3:
open: ;*
close: ((EOL))

That should do the trick.

Best regards,
Ivan

**Comment by manufv** [comment]
fine, it works very good.
thank you
