### ISSUE TITLE
ESF files

### ISSUE THREAD

**Issue by rickx** [ivan-radic/udl-documentation#15]
Hi, I kindly ask for help. 
ESF files are what you export from a sw called ETS. They're text file like this:
XXX.YYY YYY.0/2/202	NAME NAME NAME	EIS 1 'Switching' (1 Bit)	Low
ZZZ....

So you have: separation by dots and by tabs. The main separation by tabs.
The meaning would be: XXX.YYY YYY would be a hierarchy of "folders" where YYY YYY is under XXX. 0/2/202 is a group address, similar to an IP address but with "/". Then the name which may contain anything, then the data type, then 1 or more additional "columns".
What I can't solve is making notepad++ recognize the "numbers" which have the format number/number/number in most cases, or number/number. It this feasible? Thanks in advance.

**Comment by ivan-radic** [comment]
Hi Rick,

sorry about the slow reply.
Unfortunately, this is not possible.

Best regards,
Ivan
