### ISSUE TITLE
How to fold blocks of code?

### ISSUE THREAD

**Issue by elenderg** [ivan-radic/udl-documentation#17]
I'm working on a language that uses blank lines as a separator for routines.

Example:

```
To do this:
First command here.
Second command here.
Etc.
```

```
To do that:
Same pattern as the routine above.
```

What every routine has in common is the following:

They all start with the word "To".
The routine headers end with a colon.
The end of the routine body is identified by a period and a blank line below it.

How can I implement this in the UDL?

**Comment by ivan-radic** [comment]
Hi Elender,

this is not possible to define in UDL, as UDL can't use whitespace (blank lines) as keywords or delimiters.

Best regards,
Ivan

**Comment by elenderg** [comment]
Thanks.
