### ISSUE TITLE
Checking if a delimiter is preceded by whitespaces

### ISSUE THREAD

**Issue by avm19** [ivan-radic/udl-documentation#26]
I use UDL basically as a highlighter for text files, not for code. I defined two styles: one for lines starting with `>>>` and another for lines starting with `>>`. Here is an example:
```
normal text line 1
>>> LINE 2 HIGHLIGHTED TEXT STYLE 1
normal text text line 3
  >> LiNe 4 HiGhLiGhTeD TeXt StYlE 2
normal text line 5 text >> MoRe HiGhLiGhTeD TeXt StYlE 2
```
Here is how I defined it:
![image](https://user-images.githubusercontent.com/52547519/171462364-80402aaa-39fb-4061-8371-f69aa3f8e36a.png)

The problem with my current definition is that **I don't want any text highlighted in line 5**: my goal is to highlight lines starting with `>>`, but not those where it is surrounded by text. Is it possible to implement this using UDL? Any alternative suggestions?

I thought about defining my highlighting as comments, because there is the "Allow preceding whitespace" option. However, comments do not work for two reasons. First, there is only one style (I need two). Second, comments opening with `>>` will overshadow `>>>`-delimiters, so that line 2 will also be treated as a `>>`-comment.

I understand this is probably not an intended use case, but yet there might be an easy trick or functionality I haven't considered. Thanks.

**Comment by ivan-radic** [comment]
Hi there,

sorry about super slow response.
Positioning is not verified when looking for delimiters. As you noticed one exception to that rule are line comments, but that one is hard to abuse because comments are checked before any other file type. So, in one word, this can't be done.

Best regards,
Ivan
