### ISSUE TITLE
Mixed content issue

### ISSUE THREAD

**Issue by SamB** [ivan-radic/udl-documentation#3]
There's a [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content) problem in styles.css, because it refers to an `http://` URL, while the site is normally accessed using `https://`. In particular:
https://github.com/ivan-radic/udl-documentation/blob/17e90fbac9e302c878a94cd7136c8348a1ed5f3d/stylesheets/styles.css#L1
should probably be changed to:
```css
@import url(https://fonts.googleapis.com/css?family=Arvo:400,700,400italic);
```

**Comment by ivan-radic** [comment]
Fixed.
Thanks for reporting this. I wonder why I never got an e-mail notification about this issue? I could have fixed it right away.

Cheers,
Ivan
