### ISSUE TITLE
Is there a way to list the User Defined Language under the correct letter in the Language menu?

### ISSUE THREAD

**Issue by ghost** [ivan-radic/udl-documentation#36]
Is there a way to list the User Defined Language under the correct letter in the Language menu?
If yes, how do you do it?
![image](https://github.com/ivan-radic/udl-documentation/assets/62229442/2e633f47-5e94-4fd9-bbf7-17343ce7eb0c)

**Comment by ivan-radic** [comment]
Hi Katalin,

this is not possible.

Best regards,
Ivan
