### ISSUE TITLE
multi-part support for code folding

### ISSUE THREAD

**Issue by jxramos** [ivan-radic/udl-documentation#4]
I'm trying out the udl features for our bamboo build logs. The logs get broken up by bamboo into these large chunks which I'd like to section out if at all possible.

There's a phrase I'm attempting to use to do this, `Starting task` and `Finished task`, however unlike the multi-part keywords being denoted with double or single quotes there doesn't seem to be the same support for the code folding feature.

I really like udl for my own custom formatting of the various console output I retrieve from various tools. It's a good use case for highlighting structure and pointing out build errors, etc. However console output usually doesn't follow strict syntax guidelines like one would find with a formal programming language.

![bblogworkingfold](https://user-images.githubusercontent.com/13857038/31566748-d9514bca-b020-11e7-9fd2-de831e24eb63.png)
![bblogbrokenfold](https://user-images.githubusercontent.com/13857038/31566751-dc591474-b020-11e7-9bc4-425cfc62f173.png)

**Comment by ivan-radic** [comment]
Hi and thanks for reporting this.

Yes, this is a limitation of current UDL. However, it is solved in the upcoming UDL 3.0 branch (yet unpublished), so you will just have to patient until I publish UDL 3.0.

Cheers,
Ivan
