### ISSUE TITLE
add option for checking positions (maybe [partial] regex) in comments

### ISSUE THREAD

**Issue by GitMensch** [ivan-radic/udl-documentation#6]
I've rechecked an UDL for a self-made preparser for COBOL, most parts were fine or could be fixed but the last mayor point seems to be not solvable with the current UDL implementation:

"Normal" comments in fixed-form reference-format start are only defined if there is a `*` (or `/`) in column 7 - if these are found in column 6 they are ignored, if they are in column 8+ they are part of an arithmetic expression. As the later does happen often the setting active is "Line comment position: allow preceding whitespace".

Thinking again: ideally columns 1-6 are "seen" as white-space, any words there shouldn't be highlighted at all...
Do you have any suggestions how to target this issue?

**Comment by ivan-radic** [comment]
Hi,
this is not possible in UDL. Positional formatting (as in "keyword is valid only in column X") is not supported.

Cheers,
Ivan
