### ISSUE TITLE
Keywords in prefix mode: identify next word only

### ISSUE THREAD

**Issue by jannick0** [ivan-radic/udl-documentation#7]
I am referring to the bottom section of the [keywords](http://ivan-radic.github.io/udl-documentation/keywords/) documentation page: For keywors in prefix mode is it possible to restrict highlighting to the next **word** only, i.e. those tokens matching, e.g., `[0-9a-z_-]+` after the prefix only?

I am struggling for the prefix `xyz` to have in `xyz_abc(ABC,4)` only `xyz_abc` be highlighted, instead the highlighting scope goes beyond the opening bracket which should not be the case.

Please let me know if I am missing something and the issue can easily be solved.

**Comment by ivan-radic** [comment]
Hi Jannick,

this is not the job for prefix option. Instead, just define brackets as Delimiter type. That alone will prevent highlighting beyond `xyz_abc` part.

Cheers,
Ivan

**Comment by jannick0** [comment]
Hi Ivan,

got it. It works as you say.

Many thanks,
J.
