### ISSUE TITLE
prefixed keywords: highlighting of nested calls

### ISSUE THREAD

**Issue by jannick0** [ivan-radic/udl-documentation#8]
Hi Ivan,

I am struggling to configure a language with prefixed function names (i.e. prefixed keywords) such that nested function calls are highlighted. 

Currently I managed that for `x_` prefixed function names only the outer function call (`x_f`) is highlighted, the inner function call (`x_g`) is not, which should be, of course:
~~~
x_f(a, x_g(b))
~~~

Any help appreciated.

Many thanks,
J.

**Comment by ivan-radic** [comment]
Hi Jannick,

try this:
1. define `x_` as Keyword1 type, tick prefix mode
2. define `(` and `)` as the Open and Close sequence of the Delimiter1 type
3. In styler of Delimiter1 tick Nesting checkbox for Delimiter1 and Keyword1

That should give you:

`x_a`(a, `x_g`(b))

Best regards,
Ivan

**Comment by jannick0** [comment]
Hi Ivan,

great - that works perfectly!

I was not aware of this option, as I am on a translated version of npp with an a bit confusing translation of 'Nesting'. I did not understand it and I ignored it. I just switched the npp display language to English to avoid more things 'lost in translation'.

Many thanks again,
J.
